### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by joshhornby** [OliverJAsh/decode-ts#2]
Hey @OliverJAsh 

Thanks for creating this package Would be great if you could include some examples of how you'd use this lib in a production app. I have a very simple example:

```
const Todo = t.interface({
  id: t.number,
  completed: t.boolean
});

fetch('https://jsonplaceholder.typicode.com/todos')
  .then(r => r.json())
  .then(b => jsonDecodeString(t.array(Todo))(JSON.stringify(b)))
  .then(t => console.log(t));
```

But i'd be interested to see how you handle errors, how you handle the `Either` type (map, fold etc)

Thanks

**Comment by OliverJAsh** [comment]
Hey @joshhornby!

## Avoid unsafe JSON parse in `response.json`

Use `response.text` instead and let decode-ts safely parse it as JSON. This way there won't be exceptions, and a parsing error would return as a `Left`.

``` ts
fetch('https://jsonplaceholder.typicode.com/todos')
    .then(r => r.text())
    .then(b => jsonDecodeString(t.array(Todo))(b))
```

## Using Either type

The Either type is provided by io-ts which uses fp-ts under the hood. See that project for the full API. https://github.com/gcanti/fp-ts

``` ts
fetch('https://jsonplaceholder.typicode.com/todos')
    .then(r => r.text())
    .then(b => jsonDecodeString(t.array(Todo))(b))
    .then(t =>
        t.fold(
            error => {
                console.log('error', formatJsonDecodeError(error));
            },
            todo => {
                console.log('success', todo);
            },
        ),
    );
```

This could be tidied up using `Task` and the `EitherT` monad transformer from fp-ts to create a `TaskEither`:

``` ts
new TaskEither(
    new Task(() => fetch('https://jsonplaceholder.typicode.com/todos'))
        .map(r => r.text())
        .map(b => jsonDecodeString(t.array(Todo))(b)),
).fold(
    error => {
        console.log('error', formatJsonDecodeError(error));
    },
    todo => {
        console.log('success', todo);
    },
);
```

https://github.com/gcanti/fp-ts/blob/4f8cf76809d92a9658d682267c655b75d1dd49d3/examples/TaskEither.ts

**Comment by joshhornby** [comment]
Brilliant, thanks @OliverJAsh 👍
