### ISSUE TITLE
Compatibility with fp-ts and io-ts 1.0

### ISSUE THREAD

**Issue by wmaurer** [OliverJAsh/decode-ts#3]
I'd like to try out `decode-ts`, but right now its dependencies are `fp-ts ^0.6.2` and `io-ts ^0.8.2`.
Do you have plans to upgrade `decode-ts` to use version `^1` of `fp-ts` and `io-ts`?

**Comment by OliverJAsh** [comment]
Hey @wmaurer! I do plan to upgrade but I might not get the chance to do it until I need it for myself. If someone else wants to have a go, I'll be more than happy to review!

**Comment by OliverJAsh** [comment]
Fixed in v0.0.8

**Comment by wmaurer** [comment]
Thanks a lot! I had planned to look into it, but you got to it too quick for me ;-)
Nice to see you're also using https://github.com/peletom/unionize, I'm also finding it to be very good.
